---
  - name: Install packages
    hosts: webservers
    become: yes 
    tasks:
      - name: Install
        apt: pkg={{item}} state=installed update_cache=yes
        with_items:
          - nano
          - vim
